#!/bin/bash
 
server="http://ihatemylife.tk/tellme.php"
deviceName="number-1"
getParam="?device_name=$deviceName"

tellToServerIfOnline() {
  wget --spider -q "$server$getParam"
}

ifBdWorkerIsNotRunning() {
  if [ `ps aux | grep "bdWorker.py" -c` -lt 2 ]; then
    bdWorker
  fi
}

ifOnline() {
  tellToServerIfOnline

  if [ $? -lt 1 ]; then
    ifBdWorkerIsNotRunning
  else
    exit 0
  fi
}

fire() {
  ifOnline
}


fire
